project.name=lab3-web
project.version=1.0-SNAPSHOT

src.dir=src/main/java
resources.dir=src/main/resources
web.dir=src/main/webapp
test.src.dir=src/test/java

build.dir=build-ant
classes.dir=build-ant/classes
test.classes.dir=build-ant/test-classes

dist.dir=dist
reports.dir=reports
doc.dir=docs

lib.dir=lib
test.lib.dir=lib-test

jar.file=dist/lab3-web.jar
war.file=dist/lab3-web.war

checksums.dir=build-ant/checksums
manifest.file=build-ant/MANIFEST.MF

project.files.md5.name=Project-Files-MD5
project.files.sha1.name=Project-Files-SHA-1

localization.src.dir=src/main/resources/localization
localization.build.dir=build-ant/localization

music.file=src/main/resources/sounds/sugoi.wav

diff.report.file=reports/diff.txt

scp.user=s415129
scp.host=se.ifmo.ru
scp.port=2222
scp.remote.dir=~/opi
scp.file=${war.file}
scp.key=/home/vietht-hl/.ssh/seIfmo_key



alt.work.dir=build-ant/alt
alt.src.root=build-ant/alt/src
alt.build.dir=build-ant/alt-build
alt.classes.dir=build-ant/alt-build/classes

alt.src.dir=build-ant/alt/src/main/java
alt.resources.dir=build-ant/alt/src/main/resources
alt.web.dir=build-ant/alt/src/main/webapp

alt.jar.file=dist/lab3-web-alt.jar
alt.war.file=dist/lab3-web-alt.war


alt.class.package.dir=data_services
alt.old.class.name=JsonService
alt.new.class.name=AltJsonService

alt.old.variable.name=mapper
alt.new.variable.name=jsonMapper


env.java.home=/usr/lib/jvm/java-17-openjdk-amd64
env.jvm.args=-Xmx512m -Dfile.encoding=UTF-8 -Duser.language=en


server.home=/home/vietht-hl/wildfly
server.deploy.dir=${server.home}/standalone/deployments
server.log.file=build-ant/server.log
server.pid.file=build-ant/server.pid


server.context.name=lab3-web
server.deployed.war=${server.deploy.dir}/${server.context.name}.war
server.url=http://localhost:8080/${server.context.name}

team.work.dir=build-ant/team
team.zip.file=dist/team-builds.zip
team.jar.name=lab3-web.jar


history.git.root=.
history.work.dir=build-ant/history
history.report.file=reports/history-diff.patch
history.log.file=reports/history.log
history.script.file=scripts/history.sh