package models;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity representing one calculated point result.
 * <p>
 * Each record stores the submitted coordinates, radius, hit result, calculation
 * time, release timestamp, and HTTP session identifier. The entity is mapped to
 * the {@code session_results} table.
 *
 * @author viet1m96
 * @version 1.0
 */
@Entity
@Table(name = "session_results")
@Setter
@Getter
public class Point implements Serializable {
    /**
     * Primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * HTTP session identifier used to separate records of different users.
     */
    @Column(name = "jsessionid", nullable = false)
    private String sessionId;

    /**
     * Submitted x-coordinate.
     */
    @Column(name = "x", nullable = false)
    private BigDecimal x;

    /**
     * Submitted y-coordinate.
     */
    @Column(name = "y", nullable = false)
    private BigDecimal y;

    /**
     * Submitted radius value.
     */
    @Column(name = "r", nullable = false)
    private BigDecimal R;

    /**
     * Result of checking whether the point belongs to the target area.
     */
    @Column(name = "hit", nullable = false)
    private boolean hit;

    /**
     * Time spent calculating the hit result, measured in milliseconds.
     */
    @Column(name = "calculation_time", nullable = false)
    private Double calTime;

    /**
     * Timestamp when the point result was produced.
     */
    @Column(name = "released_time", nullable = false)
    private LocalDateTime releaseTime;
}
